dobot_magician:
  dobot_magician_joint_controller:
    type: "position_controllers/JointTrajectoryController"
    joints:
      - joint_base
      - joint_2
      - joint_3
      - joint_4
      - joint_gripper
      
    gains:
      joint_base:   {p: 1000.0, i: 0.0, d: 0.1, i_clamp: 0.0}
      joint_2: {p: 1000.0, i: 0.0, d: 0.1, i_clamp: 0.0}
      joint_3:  {p: 1000.0, i: 0.0, d: 0.1, i_clamp: 0.0}
      joint_4:       {p: 1000.0, i: 0.0, d: 0.1, i_clamp: 0.0}
      joint_gripper:    {p: 1000.0, i: 0.0, d: 0.1, i_clamp: 0.0}
     
  gripper_controller:
    type: "position_controllers/JointTrajectoryController"
    joints:
      - Gripper_left
      - Gripper_right
    gains:
      Gripper_left:  {p: 50.0, d: 1.0, i: 0.01, i_clamp: 1.0}
      Gripper_right:  {p: 50.0, d: 1.0, i: 0.01, i_clamp: 1.0}

